---
title: "Add-on functions to set up simulation"
output: html_document
data: August 15, 2022
---

\newcommand{\bX}{{\boldsymbol X}}
\newcommand{\bW}{{\boldsymbol W}}
\newcommand{\bZ}{{\boldsymbol Z}}


```{r default, include = FALSE, collapse = TRUE}
library(knitr)
opts_chunk$set(prompt = TRUE, comment = "")
options(width = 110)
```

This vignette explains the functions in `../codes/sim3A.R`, `../codes/sim3B.R`, and `../codes/sim3C.R`.

### Simulation settings

The proposed dynamic risk prediction using survival tree ensembles is illustrated with simulated data, wherein
the event times are generated from an irreversible multi-state model with three states: healthy, diseased, and death. 
We assume that all subjects started in the healthy state, disease onset is an intermediate event,
and death is the event of interest.
Define the time-independent predictors $\bZ = (Z_1, \ldots, Z_{10})$ as a multivariate 
normal random variable with $\mbox{E}(Z_i)=1$, $\mbox{Var}(Z_i) = 1$, and $\mbox{Cov}(Z_i, Z_j) = 0$, 
for $i, j = 1, \ldots, 10$. 
We generate the time to the first event, denoted by $D$, from a uniform distribution on $[0, 5]$.
Define the disease indicator, $\Pi$, 
where $\Pi = 1$ indicates the subject moves from the healthy state to the disease state at time $D$, 
and $\Pi= 0$ indicates the subject moves from the healthy state to death at time $D$.
The disease indicator was obtained via a logistic regression model,
\begin{equation}
\mbox{logit} \left[P\{\Pi=1\mid \bZ, \bW(D)\}\right] = \sum_{j = 1}^3 W_i(D) + \sum_{j=1}^3Z_j + \gamma,
\end{equation}
where $\gamma$ is a frailty variable following a gamma distribution with mean 1 and variance 0.5,
the element of
$\bW(t) = \{W_1(t), \ldots, W_{10}(t)\}$ is generated from $W_j(t) = a_j \{1 - \exp(-0.04t^2)\}$, 
and $a_j$ follows a uniform distribution on $[-1, 1]$, for $j = 1,\ldots,10$.
Given a subject had developed the disease at time $D$ , i.e., $\Pi = 1$, 
the residual survival time, $R$ , is then generated from the following model:
\begin{equation}
\log R = -5 + \sum_{j = 1}^3W_j(D) + \sum_{j = 1}^3Z_j^2 + \sum_{j = 1}^3 W_j(D) Z_{j} + \log(1 + D) + \gamma + \epsilon,
\end{equation}
where $\epsilon$ is a standard normal random variable. 
When $\Pi = 1$, the time to death is $T = D + R$, and the time to the intermediate event is $U = D$; 
when $\Pi = 0$, the time to death is $T = D$ and the intermediate event does not occur, i.e., $U =$ `NA`.


Let $T_L$ be the landmarkd time.
We consider the following three scenarios depending on how the landmark time and the longitudinal markers are observed:

  **Scenario A.** 
  The landmark is the intermediate event, i.e., $T_L = U$, and $\bW(\cdot)$ is observed intermittently at $t_k = k$, $k = 1,\ldots,5$. 
  
  **Scenario B.** 
  The landmark time is fixed at $T_L = a$, and $\bW(\cdot)$ is observed at the intermediate event. 
  
  **Scenario C.**
  The landmark is the intermediate event, i.e., $T_L = U$, and $\bW(\cdot)$ is observed at the intermediate event. 
  
The target probabilities for the above three scenarios are the following. 

  **Scenario A.** $P\{T\ge U + t|T\ge U, U, W(1, U), W(2, U), W(3, U), W(4, U), W(5, U), Z\}$.
  
  **Scenario B.** 
  $P\{T-a\ge t\mid T\ge a, U ,\bW(U) , \bZ\}$ if $U\le a$ and $P\{T-a\ge t\mid T\ge a, U > a,\bZ\}$ if $U>a$.
  
  **Scenario C.** $P\{T\ge U + t|T\ge U, U, W(U), Z\}$.

The above simulation corresponds to simulation Scenarios (III-A), (III-B), and (III-C) in Sun et al. (2022).

### Generating simulated data

The implementation of scenarios A, B, and C are available in 
`../codes/sim3A.R`, `../codes/sim3B.R`, and `../codes/sim3C.R`, respectively. 
The `R` codes can be loaded with the following `source()` commands.
```{R}
source("../codes/sim3A.R")
source("../codes/sim3B.R")
source("../codes/sim3C.R")
```
The `R` functions to generate the landmark data under scenarios A, B, and C, are
`simDat3A()`, `simDat3B()`, and `simDat3C()`, respectively.
These functions share a similar syntax. 
```{R}
args(simDat3A)
args(simDat3B)
args(simDat3C)
```

These functions have two common arguments, `n` and `cen` for sample size and censoring percentage at the baseline, respectively.
Three levels of censoring are currently available; 0\%, 20\%, and 40\%.
The `simDat3A()` function takes an additional argument `test` indicates whether to include $a$ in output, 
which is useful for approxmating the empirical survival probability of a testing data. 
Simulated data can be generated by specifying `n` and `cen` but are processed differently depending on 
how the landmark time and the longitudinal markers are observed.

#### Random landmark time with longitudinal predictors (Scenario A)

A simulated data from this scenario can be generated as follows. 
```{R}
set.seed(1); dat3A <- simDat3A(n = 400, cen = .2)
names(dat3A)
dat3A[10:15, c(1:5, 14:15, 64:65)]
```

The `simDat3A()` returns a `data.frame` with the following variables. 

  - `Time` is the observed survival time after $U$, e.g., $T-U$.
  - `status` is the censoring indicator; 1 if `Time` is the event of interest (death) and 0 if `Time` is censored.
  - `D` is the time from the healthy state to the diseased state. This is also the landmark time in this scenario. 
  - `Z.1`...`Z.10` are the 10 baseline predictors.
  - `W.i.j.k` are the time-dependent predictors, for $i = 1, \ldots, 10$, $j = 1, \ldots, 5$, and $k = 1, 2$.
  The variable `W.i.j.k` indicates the $i$th time-dependent predictors at time $T_j$, i.e., $W_i(T_j)$.
  The last index `k` indicates the first and the second values after applying the proposed preprocessing procedure
  to the time-dependent predictors. 
  Specifically, when the time-dependent predictor is observed at time $T_j$, we split $W_i(T_j)$ by $\{W_i(T_j), W_i(T_j)\}$. When the time-dependent predictor is not observed at time $T_j$, $W_i(T_j)$ has a value of `NA`, and 
  we split $W_i(T_j)$ by $\{-M, M\}$, for some large value $M$ such as $10^5$.


#### Fixed landmark time with longitudinal predictors measured at the intermediate event (Scenario B)

A simulated data from this scenario can be generated as follows. 
```{R}
set.seed(1); dat3B <- simDat3B(n = 400, cen = .2)
names(dat3B)
head(dat3B[, c(1:5, 14:15, 24:25)])
```

The `simDat3B()` returns a `data.frame` with the following variables. 

  - `Time` is the observed survival time after $T_L = 2$, e.g., $T - T_L$.
  - `status` is the censoring indicator; 1 if `Time` is the event of interest (death) and 0 if `Time` is censored.
  - `D` is the time from the healthy state to the diseased state. 
  This is observed if $D < T_L = 2$, otherwise `D = 2`.
  - `Z.1`...`Z.10` are the 10 baseline predictors.
  - `W.i.j` are the time-dependent predictors, for $i = 1, \ldots, 10$, and $j = 1, 2$.
  The variable `W.i.j` indicates the $i$th time-dependent predictors at time $U$, i.e., $W_i(U)$.
  The index `j` indicates the first and the second values after applying the proposed preprocessing procedure
  to the time-dependent predictors. 
  Specifically, when the time-dependent predictor is observed at time $U$, we split $W_i(U)$ by $\{W_i(U), W_i(U)\}$. When the time-dependent predictor is not observed at time $U$, $W_i(U)$ has a value of `NA`, and we split $W_i(U)$ by $\{-M, M\}$, for some large value $M$ such as $10^5$.


#### Random landmark time with longitudinal predictors measured at the intermediate event (Scenario C)

A simulated data from this scenario can be generated as follows. 
```{R}
set.seed(1); dat3C <- simDat3C(n = 400, cen = .2)
names(dat3C)
head(dat3C[, c(1:5, 14:15)])
```

The `simDat3C()` returns a `data.frame` with the following variables. 

  - `Time` is the observed survival time after $U$, e.g., $T-U$.
  - `status` is the censoring indicator; 1 if `Time` is the event of interest (death) and 0 if `Time` is censored.
  - `D` is the time from the healthy state to the diseased state. This is also the landmark time in this scenario. 
  - `Z.1`...`Z.10` are the 10 baseline predictors.
  - `W.i` are the time-dependent predictors observed at time $U$, for $i = 1, \ldots, 10$.
  Since the landmark time for this scenario is $U$, $W_i(U)$ is always observed and the proposed preprocessing procedure
  is not applied here.
  
### Computing true probability
 
Due to the complicated relationship between event times and longitudinal markers, 
deriving the closed-form expression of the true probability is challenging. 
Thus, we rely on empirical method to compute the true landmark probability using 
Monte Carlo method for this scenario.

The `R` functions used to compute the true probability under scenarios A, B, and C, are
`getTrueSurv3A()`, `getTrueSurv3B()`, and `getTrueSurv3C()`, respectively.
```{R}
args(getTrueSurv3A)
args(getTrueSurv3B)
args(getTrueSurv3C)
```
The `getTrueSurv()` functions take only one argument `dat`, which is a data frame
generated by the corresponding `simDat()` functions.
The `getTrueSurv()` functions return a list,
where the $i$th member of the list gives the empirical estimation of the true probability
for the the $i$th subject from `dat`.
The empirical probabilities are useful for evaluating model performance based on performance statistics 
such as the integrated absolute errors and the integrated mean squared errors.
 
### Reference 

- Sun, Y., Chiou, S.H., Wu, C.O., McGarry, M. and Huang, C.Y., (2022). Dynamic risk prediction using survival tree ensembles with application to Cystic Fibrosis. *Annals of Applied Statistics* (In press).

